// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFPC2pLSVTHPMKXm32Y1ypq3SHpJaCi0',
    appId: '1:182711927814:web:4b2ffd39b0729f459def87',
    messagingSenderId: '182711927814',
    projectId: 'dad-2-p',
    authDomain: 'dad-2-p.firebaseapp.com',
    storageBucket: 'dad-2-p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPSfEFtsxtTX9kah5_um5t2-zEcPH99lI',
    appId: '1:182711927814:android:2a59803e0a575f1f9def87',
    messagingSenderId: '182711927814',
    projectId: 'dad-2-p',
    storageBucket: 'dad-2-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nkUtmfHjGMwHHWuPHP_tisWE1ZP6Ccc',
    appId: '1:182711927814:ios:7cf97662ec4ee2459def87',
    messagingSenderId: '182711927814',
    projectId: 'dad-2-p',
    storageBucket: 'dad-2-p.appspot.com',
    iosBundleId: 'com.example.dad2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3nkUtmfHjGMwHHWuPHP_tisWE1ZP6Ccc',
    appId: '1:182711927814:ios:468f6e843b6d21679def87',
    messagingSenderId: '182711927814',
    projectId: 'dad-2-p',
    storageBucket: 'dad-2-p.appspot.com',
    iosBundleId: 'com.example.dad2.RunnerTests',
  );
}
